---
title: "Mapping Assignment 1"
author: "Jake Barrett"
date: "10/19/2021"
output: html_document
---

```{r packages}
library("Rcpp")
library("sf")
library("ggsn")
library("leaflet")
library("mapdata")
library("maptools")
library("OpenStreetMap")
library("rgdal")
library("tidyverse")
```

## Static Map: Minnesota's population by county

Made a map of Minnesota population by county: 

Things to add: annotation, scalebar

```{r static, fig.width=9.5, fig.height=9}
state <- map_data("state")
county <- map_data("county")
st_paul <- data.frame("x" = -93.089958, "y" = 44.953705) 

names(county)

mn <- county %>% 
  filter(region=="minnesota")

mn_pops <- read.csv("data/mn_county_pops.csv")

counties <- merge(x = mn, y = mn_pops, by.x = "subregion", by.y = "county", all = TRUE)

ggplot() + geom_polygon(data = state, aes(x=long, y = lat, group = group),
                        fill = "white", color="black") + 
           geom_polygon(data = mn, aes(x=long, y = lat, group = group),
                        fill = "gray", color="black") + 
          geom_polygon(data = counties, aes(x=long, y=lat, group=group, fill = population), color = "white") + 
          geom_point(data = st_paul, aes(x=x,y=y), color="black", shape=8, size=3) + 
  scale_fill_viridis_c(option = "D", trans = "log10") + 
  coord_fixed(xlim = c(-98, -90),  ylim = c(43, 50), ratio = 1.3) + 
  xlab("Longitude") + ylab("Latitude") + ggtitle("Population by County, MN") + 
  labs(caption="Above Map: Population of Minnesota by county.") + 
  north(counties, location = "bottomleft", scale = 0.05, symbol = 12, anchor = c(x= -91.5, y= 49)) + 
  scalebar(counties, dist = 50, dist_unit = "mi", transform = TRUE, model = "WGS84", location = "bottomleft", st.dist = 0.05, st.size = 3, anchor = c(x=-92,y=45)) + 
  theme(plot.caption=element_text(size=15, hjust=0, margin=margin(15,0,0,0)))
```
$~$

**Data sampled from Minnesota Compass: https://www.mncompass.org/profiles/county**


## Interactive Map: Alpine Creek Lakes 

```{r interactive map}
alpine_creekOGR <- readOGR("./data/Mapping Assignment 1.kml")

alpine_creekOGR@data$Description <- c("Rainbow Trout", "Fish-less", "Arctic Grayling, Westslope Cutthroat Trout", "Westslope Cutthroat Trout", "California Golden Trout", "Arctic Grayling, Rainbow Trout, Westslope Cutthroat Trout", "Rainbow Trout, Westslope Cutthroat Trout", "Fish-less", "Rainbow Trout, Westslope Cutthroat Trout", "Westslope Cutthroat Trout")

  leaflet(alpine_creekOGR) %>% 
  addTiles(group = "OSM")%>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB") %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap, group = "NatGeo") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "ESRI") %>%
  setView(lng = -114.97222222222223, lat = 43.907222222222224, zoom = 13.4) %>%
  addWMSTiles("https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WmsServer", layers = 
                "0") %>%
  addMiniMap(zoomLevelOffset = -4) %>%
  addScaleBar() %>% 
  addLayersControl(
            baseGroups = c("CartoDB", "NatGeo", "ESRI"),
            options = layersControlOptions(collapsed = FALSE)) %>%
  addCircleMarkers(popup = alpine_creekOGR@data$Name,
                   label = alpine_creekOGR@data$Description,
                   weight = 2,
                   color = "grey",
                   fillColor = "red",
                   fillOpacity = 0.7) %>%
   addScaleBar()
```
